### ISSUE TITLE
install conflicts.  pip install -r requirements.txt

### ISSUE THREAD

**Issue by wonzin** [showlab/all-in-one#10]
I tried what the README.md have stated.

conda create -n allinone python=3.7
source activate allinone
cd [Path_To_This_Code]
pip install -r requirements.txt

However when pip install -r requirements.txt, the following error occurs.

$ pip install -r requirements.txt
Collecting absl-py==0.13.0
  Downloading absl_py-0.13.0-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.1/132.1 kB 5.2 MB/s eta 0:00:00
Collecting addict==2.4.0
  Downloading addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting aiohttp==3.8.1
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.9 MB/s eta 0:00:00
Collecting aiosignal==1.2.0
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
**ERROR: Could not find a version that satisfies the requirement apex==0.1 (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1**

Can I modify the requirements.txt file?

**Comment by wonzin** [comment]
I think the problem is occured because 'requirements.txt' sorts the the library in abc order.


--------------------------------
It was not the error of library order, but only the problem of apex.

I erased the apex==0.1 from the 'requriements.txt'.
And download apex from here. 
https://github.com/NVIDIA/apex

**Comment by FingerRec** [comment]
Thanks for your feedback.
