### ISSUE TITLE
A minor question on Annotation files

### ISSUE THREAD

**Issue by wonzin** [showlab/all-in-one#13]
https://drive.google.com/drive/folders/1XTAAvx-d3BOyxkEzzN61tnbUkRH5AFi5

Annotation>msvd

Is 'msrvtt_mc_text.jsonl' a typo? Or do I miss something?

As the folder name is 'msvd', it seems like 'msvd_mc_text.josnl' is a resonable name.

**Comment by FingerRec** [comment]
Yes, it's a typo
Thanks for reminding, just ignore this file.
