### ISSUE TITLE
all-in-one/config.py     what is 'msrvttqa_label_size'?

### ISSUE THREAD

**Issue by wonzin** [showlab/all-in-one#14]
This one looks resonable.
![msrvtt1](https://user-images.githubusercontent.com/74485327/192132343-16c774e6-8b34-44af-b79b-6835d568f98b.png)

However, msrvttqa_label_size is used 5 times including where the def is not related to 'msrvttqa'.

Is 'msrvttqa_label_size' has special meaning?

![msrvtt2](https://user-images.githubusercontent.com/74485327/192132336-c6627870-d9d2-4bf3-a438-22d5413858f5.png)

![msrvtt3](https://user-images.githubusercontent.com/74485327/192132325-ec4b3474-3dd8-4b47-b080-1709447a764c.png)

![msrvtt4](https://user-images.githubusercontent.com/74485327/192132338-858043be-a319-4a00-9047-8f913ebbf5cf.png)

**Comment by FingerRec** [comment]
for open end VQA, this task ask the model to select one class from all voculbary (label size)

**Comment by wonzin** [comment]
Thank you!
