### ISSUE TITLE
add model to Huggingface 

### ISSUE THREAD

**Issue by AK391** [showlab/all-in-one#2]
Hi, would you be interested in adding all-in-one to [Hugging Face Hub](https://huggingface.co/models)? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. We can setup an organization or a user account under which all-in-one can be added similar to github.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by FingerRec** [comment]
hi ak:
Thanks for your attention.
I'd like to share this project in Hugging Face Hub. I'll apply a Space and push our code in this platform.

**Comment by AK391** [comment]
@FingerRec Great when the space is ready, you can also add a badge to the readme so users can find it

for example: 

- Integrated into [Huggingface Spaces 🤗](https://huggingface.co/spaces) using [Gradio](https://github.com/gradio-app/gradio). Try out the Web Demo: [![Hugging Face Spaces](https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue)](https://huggingface.co/spaces/showlab/all-in-one)
