### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by danylo-kelvich** [showlab/all-in-one#3]
Hi! I want to test video retrieval with `all-in-one-base.ckpt` on MSR-VTT and see the metrics to compare with the paper. Can you please help with the command?
I tried the following command but it started to train the model and I only need testing.
`python run.py with data_root=data/ num_gpus=2 num_nodes=1 per_gpu_batchsize=32 task_finetune_only_ind_itc_msrvtt_randaug num_frames=3 load_path="pretrained/all-in-one-base.ckpt"`

**Comment by FingerRec** [comment]
Hi Daniel:
Our work focus on general pre-training and the provided weight is pre-trained weight. 

You need to fine tune this model for downstream fast retrieval, look at Section Downstream Tasks-Text-video Retrieval for details.

BTW, be careful. :)

**Comment by pribadihcr** [comment]
> Hi Daniel: Our work focus on general pre-training and the provided weight is pre-trained weight.
> 
> You need to fine tune this model for downstream fast retrieval, look at Section Downstream Tasks-Text-video Retrieval for details.
> 
> BTW, be careful. :)

where is the section README?
