### ISSUE TITLE
downstream task checkpoint

### ISSUE THREAD

**Issue by fangz-cs** [showlab/all-in-one#4]
Thank you very much for your excellent code sharing, and can you share your downstream tasks checkpoints?

**Comment by FingerRec** [comment]
Of course.
But we take 10+ datasets and produce a large number of downstream checkpoints for each dataset.

The checkpoint for which dataset you need? Maybe I can upload one to google driver if you have difficult in running downstream code.

**Comment by fangz-cs** [comment]
ok,i just need the VideoQA checkpoint, both open ended and multichoice.Thank you!

**Comment by FingerRec** [comment]
We upload trained weight on downstream VQA (tgif-frame dataset).
The checkpoint is in google driver:

https://drive.google.com/file/d/1yGSjyhcJT0tGURyFT4wa-iVXFOhLP29T/view?usp=sharing

Pls consider star our code if helpful. :)
