### ISSUE TITLE
Annotation (Caption file) missing for HowTo100M dataset

### ISSUE THREAD

**Issue by jacobswan1** [showlab/all-in-one#6]
Dear author,

Thank you for your great effort, especially the very neat & organized code for data loading! That helps a lot for our research. In the meanwhile, I'm wondering do you plan to release the processed caption file for the HowTo100M dataset? As it seems it's not released in the Google Driver. I understand that you must use the official provided caption file but just would like to check with you first as your processed file might be fitting the data loader more easily.

Appreciate your help in advance.

Regards

**Comment by FingerRec** [comment]
Hi jacbobswan1:

We download caption files from https://www.rocq.inria.fr/cluster-willow/amiech/howto100m/howto100m_captions.zip.
We decompress this file in the same directory of original video, load captions as below (line119-121) in hotwo100m.py:.


```python
    def get_caption_path(self, sample):
        # example xx/xx/xx.mp4 -> xx.csv
        return os.path.join(self.caption_dir, sample.split('/')[-1].split('.')[0] + '.csv')
```

If you have difficult in downloading howto100m, you can refer to [MIL-NCE](https://github.com/antoine77340/MIL-NCE_HowTo100M) for more information.

**Comment by jacobswan1** [comment]
Thank you for the instruction! I'll follow as you suggested. 

Yours
Jacob
